# Generated by Django 2.1.7 on 2019-05-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PumpManager', '0002_auto_20190509_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PumpManager.Community')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PumpManager.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=3, max_digits=5)),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PumpManager.Mix')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='cathegory',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='song',
            name='type',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='location',
            name='game',
            field=models.ManyToManyField(blank=True, null=True, to='PumpManager.Version'),
        ),
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PumpManager.Location'),
        ),
        migrations.AddField(
            model_name='song',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PumpManager.Version'),
        ),
    ]
