# Generated by Django 2.1.7 on 2019-05-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PumpManager', '0004_chart_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PumpManager.Player'),
        ),
    ]
