# Generated by Django 2.1.7 on 2019-05-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PumpManager', '0005_stage_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(max_length=10),
        ),
    ]
