# Generated by Django 2.1.7 on 2019-05-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PumpManager', '0010_auto_20190529_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='adress',
            new_name='address',
        ),
    ]
