# Generated by Django 2.1.7 on 2019-05-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PumpManager', '0011_auto_20190529_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='version',
        ),
        migrations.AddField(
            model_name='song',
            name='mix',
            field=models.ManyToManyField(to='PumpManager.Mix'),
        ),
    ]
