# Generated by Django 2.1.7 on 2019-05-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PumpManager', '0014_auto_20190529_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
