# Generated by Django 2.1.7 on 2019-05-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PumpManager', '0003_auto_20190518_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField()),
                ('type', models.CharField(max_length=40)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PumpManager.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=15)),
                ('grade', models.CharField(max_length=4)),
                ('time', models.DateTimeField()),
                ('chart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PumpManager.Chart')),
            ],
        ),
    ]
