# Generated by Django 2.1.7 on 2019-05-29 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PumpManager', '0013_stage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
